/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infocertificado;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.KeyStore;
import java.security.Provider;
import java.security.cert.CertificateParsingException;
import java.security.cert.X509Certificate;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Enumeration;
import javax.naming.spi.DirStateFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.bouncycastle.asn1.DERObject;
import org.bouncycastle.asn1.DERObjectIdentifier;
import org.bouncycastle.asn1.DEROctetString;
import org.bouncycastle.asn1.DERPrintableString;
import org.bouncycastle.asn1.DERSequence;
import org.bouncycastle.asn1.DERTaggedObject;
import org.bouncycastle.asn1.DERUTF8String;
import org.bouncycastle.x509.extension.X509ExtensionUtil;

/**
 *
 * @author geova
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }
    
    private static SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");   
      
      
    public static final DERObjectIdentifier RESPONSAVEL = new DERObjectIdentifier("2.16.76.1.3.2");   
    public static final DERObjectIdentifier CNPJ = new DERObjectIdentifier("2.16.76.1.3.3"); 
    
    private static void getInfoAdicionais(X509Certificate certificate,String re)  
            throws CertificateParsingException {  
  
        re = re +"--------------------------------------------------------"+ "\n";  
        Collection<?> alternativeNames = X509ExtensionUtil.getSubjectAlternativeNames(certificate);  
        for (Object alternativeName : alternativeNames) {  
            if (alternativeName instanceof ArrayList) {  
                ArrayList<?> listOfValues = (ArrayList<?>) alternativeName;  
                Object value = listOfValues.get(1);  
                if (value instanceof DERSequence) {  
                    DERSequence derSequence = (DERSequence) value;  
                    DERObjectIdentifier derObjectIdentifier = (DERObjectIdentifier) derSequence.getObjectAt(0);  
                    DERTaggedObject derTaggedObject = (DERTaggedObject) derSequence.getObjectAt(1);  
                    DERObject derObject = derTaggedObject.getObject();  
  
                    String valueOfTag = "";  
                    if (derObject instanceof DEROctetString) {  
                        DEROctetString octet = (DEROctetString) derObject;  
                        valueOfTag = new String(octet.getOctets());  
                    }   
                    else if (derObject instanceof DERPrintableString) {  
                        DERPrintableString octet = (DERPrintableString) derObject;  
                        valueOfTag = new String(octet.getOctets());  
                    }   
                    else if (derObject instanceof DERUTF8String) {  
                        DERUTF8String str = (DERUTF8String) derObject;  
                        valueOfTag = str.getString();  
                    }  
                      
                    if ((valueOfTag != null) && (!"".equals(valueOfTag))) {  
                        if (derObjectIdentifier.equals(RESPONSAVEL)) {  
                            re = re +"Nome do Responsavel: " + derObjectIdentifier + " - " + valueOfTag + "\n";  
                        }  
                        else if (derObjectIdentifier.equals(CNPJ)) {  
                            re = re +"CNPJ...............: " + derObjectIdentifier + " - " + valueOfTag+ "\n";    
                        }  
                        else {  
                            re = re + "OID................: " + derObjectIdentifier + " - " + valueOfTag+ "\n";  
                        }
                        info(re);
                    }  
                }  
            }  
        }  
    }  
      
    /** 
     * Log ERROR. 
     *  
     * @param error 
     */  
    public static void error(String error) {  
        results.setText("| ERROR: " + error);
    }  
  
    /** 
     * Log INFO. 
     *  
     * @param info 
     */  
    private static void info(String info) {  
        //System.out.println("| INFO: " + info);
        results.setText("| INFO: " + info);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        verificar = new javax.swing.JButton();
        caminho = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        results = new javax.swing.JTextArea();
        senha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InfoCertificado");
        setResizable(false);

        verificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infocertificado/icons8_ok_25px.png"))); // NOI18N
        verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarActionPerformed(evt);
            }
        });

        caminho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infocertificado/icons8_search_25px.png"))); // NOI18N
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        results.setColumns(20);
        results.setRows(5);
        jScrollPane1.setViewportView(results);

        senha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setText("Caminho Certificado");

        jLabel2.setText("Senha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(caminho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verificar)))
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(caminho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(senha)
                    .addComponent(verificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarActionPerformed
        
        try {
            String re = "";
            String caminhoDoCertificadoDoCliente = caminho.getText();
            String senhaDoCertificadoDoCliente = senha.getText();            
              
            InputStream entrada = new FileInputStream(caminhoDoCertificadoDoCliente);  
            KeyStore ks = KeyStore.getInstance("pkcs12");  
            try {  
                ks.load(entrada, senhaDoCertificadoDoCliente.toCharArray());  
            } catch (IOException e) {  
                JOptionPane.showMessageDialog(null, "Senha do Certificado Digital incorreta ou Certificado inválido.");
                //throw new Exception("Senha do Certificado Digital incorreta ou Certificado inválido.");  
            }  
              
            Provider pp = ks.getProvider();  
            re = "--------------------------------------------------------\n";  
            re = re + "Provider   : " + pp.getName()+ "\n";  
            re = re + "Prov.Vers. : " + pp.getVersion()+ "\n";   
            re = re + "KS Type    : " + ks.getType()+ "\n";   
            re = re + "KS DefType : " + KeyStore.getDefaultType()+ "\n";    
      
            String alias = null;  
            Enumeration <String> al = ks.aliases();  
            while (al.hasMoreElements()) {  
                alias = al.nextElement();  
                re = re +  "--------------------------------------------------------\n";  
                if (ks.containsAlias(alias)) {  
                    re = "Alias exists : '" + alias + "'\n";  
                      
                    X509Certificate cert = (X509Certificate) ks.getCertificate(alias);  
                    re = re +  "Versão      : '" + cert.getVersion() + "'"+ "\n";   
                    re = re +  "Numero Serial : '" + cert.getSerialNumber() + "'"+ "\n";  
                    re = re +  "SigAlgName   : '" + cert.getSigAlgName() + "'"+ "\n";   
                    re = re +  "Válido de    : '" + dateFormat.format(cert.getNotBefore()) + "'" + "\n";  
                    re = re + "Válido até   : '" + dateFormat.format(cert.getNotAfter()) + "'" + "\n";  
  
                    getInfoAdicionais(cert,re);  
                } else {
                    re = re +  "Alias Não Existe : '" + alias + "'"+ "\n";  
                }  
                info(results.getText() + "\n" + re);   
            }  
        } catch (Exception e) {  
            e.printStackTrace();  
        } 
    }//GEN-LAST:event_verificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("Buscar imagem");
        file.setApproveButtonText("Selecionar");
        file.setApproveButtonToolTipText("Cancelar");
        
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int retorno = file.showOpenDialog(this);

        if(retorno == JFileChooser.APPROVE_OPTION){
            File arqu = file.getSelectedFile().getAbsoluteFile();
            caminho.setText(arqu.getPath());
            
        }
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField caminho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JTextArea results;
    private javax.swing.JTextField senha;
    private javax.swing.JButton verificar;
    // End of variables declaration//GEN-END:variables
}
